name: Test Docker Build

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  dockerize_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: thecoderepublic
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push linux/amd64 with Dockerfile
      - name: Build and push amd64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: thecoderepublic/mara:latest

      # Build and push linux/arm64 with Dockerfile_arm64
      - name: Build and push arm64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile_arm64
          platforms: linux/arm64
          push: true
          tags: thecoderepublic/mara:arm64

      - name: Show pushed images
        run: |
          echo "Pushed images:"
          echo "thecoderepublic/mara:latest (amd64)"
          echo "thecoderepublic/mara:arm64 (arm64)"